version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - INSTANT_APP_ID=${INSTANT_APP_ID}
      - INSTANT_APP_ADMIN_TOKEN=${INSTANT_APP_ADMIN_TOKEN}
    develop:
      watch:
        - path: ./main_api
          target: /app/main_api
          action: sync
        - path: ./messaging
          target: /app/messaging
          action: sync