version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - .:/app
    develop:
      watch:
        - path: ./fastapi
          target: /app/fastapi
          action: sync
        - path: ./messaging
          target: /app/messaging
          action: sync
